---
- name: Cấu hình firewall và cài Docker cho toàn bộ VM
  hosts: all
  become: true
  roles:
    - role: firewall
      tags: firewall
    - role: docker
      tags: docker

- name: Deploy database
  hosts: dbservers
  become: true
  roles:
    - role: database
      tags: database

- name: Deploy web app
  hosts: webservers
  become: true
  roles:
    - role: webapp
      tags: webapp

- name: Deploy load balancer
  hosts: loadbalancer
  become: true
  roles:
    - role: loadbalancer
      tags: loadbalancer