all:
  children:
    loadbalancer:
      hosts:
        lb1:
          ansible_host: 192.168.39.73

    webservers:
      hosts:
        web1:
          ansible_host: 192.168.39.71
        web2:
          ansible_host: 192.168.39.54

    dbservers:
      hosts:
        db1:
          ansible_host: 192.168.39.15